services:
  django:
    build: .
    command:
      sh -c "python manage.py collectstatic --no-input && 
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < group.py &&
             python manage.py shell < createsuperuser.py &&
             gunicorn dj_project.wsgi:application -b 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./dj_project:/app
      - static:/app/static
      - media:/media
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5400:5432" # for plug in to db locally

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/var/www/html/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static:
  postgres_data:
  media:
