# Generated by Django 4.2 on 2023-05-31 20:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_share', '0002_alter_photo_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('photo', 'author')},
        ),
    ]
